name: Latex test
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: "recursive"
    - name: install packages
      run: sudo apt-get install -y latexmk
    - name: tlmgr init
      run:  tlmgr init-usertree
    - name: tlmgr update
      run: tlmgr update --all
    - name: test acm
      run: make acm_test.pdf
    - name: test ieee
      run: make ieee_test.pdf
